# Generated by Django 5.0.6 on 2024-06-08 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jjapp", "0002_notification"),
    ]

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=50)),
                ("last_name", models.CharField(max_length=50)),
                ("date_of_birth", models.DateField()),
                ("admission_date", models.DateField()),
                ("grade", models.CharField(max_length=10)),
                ("performance", models.TextField()),
                ("attendance_records", models.TextField()),
                ("disciplinary_actions", models.TextField()),
                ("total_fee", models.DecimalField(decimal_places=2, max_digits=10)),
                ("remaining_fee", models.DecimalField(decimal_places=2, max_digits=10)),
                ("attendance_percentage", models.FloatField()),
            ],
        ),
    ]
