# Generated by Django 5.0.6 on 2024-06-08 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jjapp", "0003_student"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
